### PR TITLE
Frontend User role authorization

### PR DESCRIPTION
**Pull request by mhypolit**
This apply user roles to front end code.  It restricts button and views to correct roles. Solve #53,

### CODE REVIEW

**Comment by jdjfoley** [comment]
Suggestions:
You're using ui-sref to navigate to postEdit and using ng-click to remove most.
I feel like we should always use ng-click.

**Comment by jdjfoley** [comment]
When updating user role, session remains the same. Session should be updated with new roles

**Comment by mhypolit** [comment]
Note: You will see three file IUserRepository, UserRepository, and AuthUserRoleDTO, I created these while I was waiting for testing and didn't want to loose them so I push them, they do not have any affect on the program right now.

**Comment by jdjfoley** [comment]
Another issue found, I can remove both roles. 1 role should be required. If I go to dash with no roles I can no longer see anything.

**Pull request merged**
